config/routes.rb
Rails.application.routes.draw do
  resources :labels
  resources :users, only: [:new,:create,:show]
    namespace :admin do
      resources :users,only: [:index,:new,:create,:edit,:update,:destroy]
    end
  resources :sessions, only: [:new, :create, :destroy]
  resources :tasks
  root to: 'tasks#index'
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
                    before_validation { email.downcase! }
  has_many :tasks,dependent: :destroy
  has_secure_password
  validates :password, presence: true, on: :create
  validates :password, length: { maximum: 30 }, allow_blank: true, on: :update
  before_destroy :destroy_action
  before_update :update_action

  private

  def destroy_action
    if User.where(admin: true).count == 1 && self.admin
      throw(:abort)
    end
  end

  def update_action
    user = User.where(id: self.id).where(admin: true)
    if User.where(admin: true).count == 1 && user.present? && self.admin == false
      errors.add(:admin, 'から外せません。最低一人の管理者が必要です')
      throw(:abort)
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]
  before_action :not_logged_in
  before_action :not_admin_user

  def index
    @users = User.all.includes(:tasks)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'ユーザー情報を変更しました'
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: "#{@user.name}さんのユーザーデータを削除しました"
    else
      redirect_to admin_users_path, notice: "最低一人の管理者が必要なため#{@user.name}さんを削除できません"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def not_admin_user
    if current_user.admin == false
      redirect_to root_path, notice: 'アクセス権限がありません'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in,only: [:new,:create]
  before_action :not_logged_in,only:[:show]
  before_action :forget_user,only: [:show]
  PER = 10

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks.all
  end

    private

    def user_params
      params.require(:user).permit(:name,:email,:password,:password_confirmation)
    end

    def forget_user
      if current_user.admin == false
        if current_user.id != params[:id].to_i
          redirect_to root_path
        end
      end
    end
  end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_with(model: [:admin, @user], local: true) do |f| %>
  <%= render 'common/error', variable: @user %>
  <table>
    <tr>
      <td><%= f.label :name, '名前' %></td>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td><%= f.label :email, 'メールアドレス' %></td>
      <td><%= f.email_field :email %></td>
    </tr>
    <tr>
      <td><%= f.label :password, 'パスワード' %></td>
      <td><%= f.password_field :password %></td>
    </tr>
    <tr>
      <td><%= f.label :password_confirmation, 'パスワード確認' %></td>
      <td><%= f.password_field :password_confirmation %></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td><%= f.submit '登録' %></td>
    <tr>
  </table>
<% end %>

app/views/admin/users/edit.html.erb
<div class="container">
  <%= form_with(model: [:admin, @user], local: true) do |f| %>
    <%= render 'common/error', variable: @user %>
    <table>
      <tr>
        <td><%= f.label :name, '名前' %></td>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <td><%= f.label :email, 'メールアドレス' %></td>
        <td><%= f.email_field :email %></td>
      </tr>
      <tr>
        <td><%= f.label :admin, '管理者' %></td>
        <%= f.hidden_field :admin, value: false %>
        <td><%= f.check_box :admin, {}, true, false %></td>
      </tr>
    </table>
    <hr>
    <p>パスワードを変更する場合は以下も入力してください</p>
    <table>
      <tr>
        <td><%= f.label :password, 'パスワード' %></td>
        <td><%= f.password_field :password %></td>
      </tr>
      <tr>
        <td><%= f.label :password_confirmation, 'パスワード確認' %></td>
        <td><%= f.password_field :password_confirmation %></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td><%= f.submit '登録' %></td>
      <tr>
    </table>
  <% end %>
  <hr>
  <%= link_to 'ユーザーデータを削除する', admin_user_path(@user.id), method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <%= link_to '新規ユーザー登録', new_admin_user_path %>
  <div class="users">
    <table>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.name, user_path(user.id) %></td>
          <td>タスク数:<%= user.tasks.count %></td>
          <td>
          <%= link_to '編集・削除', edit_admin_user_path(user.id) %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="container">
  <%= form_with(model: [:admin, @user], local: true) do |f| %>
    <%= render 'common/error', variable: @user %>
    <table>
      <tr>
        <td><%= f.label :name, '名前' %></td>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <td><%= f.label :email, 'メールアドレス' %></td>
        <td><%= f.email_field :email %></td>
      </tr>
      <tr>
        <td><%= f.label :password, 'パスワード' %></td>
        <td><%= f.password_field :password %></td>
      </tr>
      <tr>
        <td><%= f.label :password_confirmation, 'パスワード確認' %></td>
        <td><%= f.password_field :password_confirmation %></td>
      </tr>
      <tr>
        <td><%= f.label :admin, '管理者' %></td>
        <%= f.hidden_field :admin, value: false %>
        <td><%= f.check_box :admin, {}, true, false %></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td><%= f.submit '登録' %></td>
      <tr>
    </table>
  <% end %>
</div>