config/routes.rb
Rails.application.routes.draw do
  resources :labels
  resources :users, only: [:new,:create,:show]
    namespace :admin do
      resources :users,only: [:index,:new,:create,:edit,:update,:destroy]
    end
  resources :sessions, only: [:new, :create, :destroy]
  resources :tasks
  root to: 'tasks#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EveryleafExam</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <header class="header">
        <% if logged_in? %>
          <%= link_to '一覧', root_path %>
          <%= link_to 'マイページ', user_path(current_user.id) %>
          <%= link_to 'ログアウト', session_path(current_user.id), method: :delete, data: {confirm: 'ログアウトしてよろしいですか？'} %>
          <% if current_user.admin %>
            <%= link_to '管理', admin_users_path %>
          <% end %>
        <% else %>
          <%= link_to 'ユーザー登録', new_user_path %>
          <%= link_to 'ログイン', new_session_path %>
        <% end %>
      </header>
      <div class="flash_message">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>
      </div>
      <%= yield %>
    </body>
  </html>